# -------------------------------------------------------
# 1. Calculation Phase (Always Runs)
# -------------------------------------------------------
- name: "Calculate disk parameters for Disk {{ disk_index }}"
  set_fact:
    src_ds_name: "{{ disk_item.value.backing_filename.split(']')[0] | replace('[', '') }}"
    src_file_path: "{{ disk_item.value.backing_filename.split('] ')[1] }}"
    # Calculate Size in GB, round up
    vol_size_gb: "{{ ((disk_item.value.capacity_in_kb | int) / 1048576) | round(0, 'ceil') | int }}G"
    dest_vol_name: "{{ target_vm_name | lower }}-disk-{{ disk_index }}"

- name: Construct full source path
  set_fact:
    full_vmdk_path: "/vmfs/volumes/{{ src_ds_name }}/{{ src_file_path }}"
    temp_rdm_path: "/vmfs/volumes/{{ src_ds_name }}/{{ target_vm_name }}_temp_{{ disk_index }}.vmdk"
    # The ESXi host in inventory to run SSH commands on
    target_esxi: "{{ groups['hypervisors'][0] }}"

# -------------------------------------------------------
# 2. Dry Run Reporting
# -------------------------------------------------------
- name: "[DRY RUN] Display Plan"
  ansible.builtin.debug:
    msg:
      - "---------------------------------------------------"
      - "ACTION: Would migrate Disk {{ disk_index }}"
      - "SOURCE: {{ full_vmdk_path }}"
      - "TARGET: FlashArray Volume '{{ dest_vol_name }}' ({{ vol_size_gb }})"
      - "HOST:   Connect to Pure Host Object '{{ pure_host_name }}'"
      - "EXEC:   Run vmkfstools on ESXi host '{{ target_esxi }}'"
      - "---------------------------------------------------"
  when: dry_run | bool

# -------------------------------------------------------
# 3. Execution Phase (Skipped if Dry Run)
# -------------------------------------------------------
- name: Create Volume on FlashArray
  purestorage.flasharray.purefa_volume:
    name: "{{ dest_vol_name }}"
    size: "{{ vol_size_gb }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_api_token }}"
    state: present
  delegate_to: localhost
  when: not dry_run | bool

- name: Connect Volume to ESXi Host on FlashArray
  purestorage.flasharray.purefa_host:
    name: "{{ pure_host_name }}"
    volume: "{{ dest_vol_name }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_api_token }}"
    state: present
  delegate_to: localhost
  when: not dry_run | bool

- name: Get Volume Serial from FlashArray
  purestorage.flasharray.purefa_info:
    gather_subset: volumes
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_api_token }}"
  delegate_to: localhost
  register: fa_info
  when: not dry_run | bool

- name: Calculate Volume NAA ID
  set_fact:
    vol_naa: "naa.624a9370{{ fa_info.purefa_info.volumes[dest_vol_name].serial | lower }}"
  when: not dry_run | bool

- name: Rescan HBAs on ESXi
  community.vmware.vmware_host_scanhba:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    esxi_hostname: "{{ target_esxi }}"
    refresh_storage: true
    rescan_hba: true
    rescan_vmfs: true
  delegate_to: localhost
  when: not dry_run | bool
# ----------------------------------------------

- name: Wait for FlashArray volume to be visible on ESXi
  ansible.builtin.wait_for:
    path: "/vmfs/devices/disks/{{ vol_naa }}"
    timeout: 60
    state: present
  delegate_to: "{{ target_esxi }}"
  when: not dry_run | bool

- name: Clone VMDK to FlashArray Volume (RDM Inject)
  ansible.builtin.command: >
    vmkfstools -i "{{ full_vmdk_path }}" 
    -d rdmp:/vmfs/devices/disks/{{ vol_naa }} 
    "{{ temp_rdm_path }}"
  delegate_to: "{{ target_esxi }}"
  register: clone_out
  when: not dry_run | bool

# -------------------------------------------------------
# 4. Cleanup Phase (Skipped if Dry Run)
# -------------------------------------------------------
- name: Remove temporary RDM mapping file
  ansible.builtin.file:
    path: "{{ temp_rdm_path }}"
    state: absent
  delegate_to: "{{ target_esxi }}"
  when: not dry_run | bool

- name: Disconnect Volume from ESXi Host
  purestorage.flasharray.purefa_host:
    name: "{{ pure_host_name }}"
    volume: "{{ dest_vol_name }}"
    fa_url: "{{ fa_url }}"
    api_token: "{{ fa_api_token }}"
    state: absent
  delegate_to: localhost
  when: not dry_run | bool

- name: Final Rescan to cleanup dead paths
  community.vmware.vmware_host_scanhba:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    esxi_hostname: "{{ target_esxi }}"
    refresh_storage: true
    rescan_hba: true
    rescan_vmfs: true
  delegate_to: localhost
  when: not dry_run | bool
